## Main
baseURL = "https://ev1lm0rty.com"
languageCode = "en-us"
title = "ev1lm0rty"
theme = "cactus"
copyright = "Shubham Arya"

## Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

#[[menu.main]]
#name = "Books"
#url = "/books"
#weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4


[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  dateform        = "2 Jan, 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006 15:04"
  colortheme = "dark" # dark, light, white, or classic
  # rss = true # generate rss feed. default value is false
  # googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default

  # Home page settings
  description = "Hello World..!!! This is Shubham Arya (ev1lm0rty), I am an InfoSec geek with a knack for automating boring stuff. I Love playing CTFs and Wargames in my free time. This website highlights my work (most of it is just the stuff I make in my free time). If you like, you can contribute to it too and maybe [buy me a beer](https://buymeacoffee.com/ev1lm0rty) :)"
  mainSection = "posts"
  showAllPostsOnHomePage = true
  postsOnHomePage = 5
  tagsOverview = false
  showProjectsList = true
  projectsUrl = "https://github.com/ev1lm0rty"


  ## Post page settings
  show_updated = true
  showReadTime = false

## Social Media URLS
  [[params.social]]
    name = "github"
    link = "https://github.com/ev1lm0rty"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/iamshubhamarya8"
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/ev1lm0rtyy"
  [[params.social]]
    name = "reddit"
    link = "https://reddit.com/user/iamnobody_8"
  [[params.social]]
    name = "email"
    link = "sec.ev1lm0rty@gmail.com"

[imaging]
resampleFilter = "box"
bgColor = "#ffffff"
anchor = "center"
